version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: "WEB-IDENTITY-PROFILE"
          role-arn: "arn:aws:iam::100682289518:role/circleci-role2"
          role-session-name: example-session
          aws-region: ap-southeast-1
      - run:
          name: List-ECR-Repositories
          command: |
            aws ecr describe-repositories
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
